plugins {
    id 'com.android.application'
}

android {
    namespace 'fr.manustream.radio'
    compileSdk 35

    defaultConfig {
        applicationId 'fr.manustream.radio'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0-test'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
